Testing finish-release scripts

diff --git a/src/shell/assert b/src/shell/assert
--- a/src/shell/assert
+++ b/src/shell/assert
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+source "$RAUTILS_PATH/src/git/git"
+
 assert::env_exist() {
   result=$(env | awk -F '=' "/$1/ {print \$1}" | grep -c -E -i "^$1\$")
   if [[ ! $result -eq 1 ]]; then
@@ -13,8 +15,9 @@ assert::rautils_env_exist() {
 }
 
 assert::total_arguments() {
+  on_error=${3:-Waiting for $2 parameters}
   if [[ "$1" -ne "$2" ]]; then
-    sout::error " Waiting for $2 parameters"
+    sout::error "$on_error"
     exit 1
   fi
 }
@@ -29,6 +32,22 @@ assert::arguments_more_than() {
 assert::is_valid_json() {
   if ! jq -e . >/dev/null 2>&1 <<<"$1"; then
     sout::error " Invalid JSON format: $1"
+    exit 1
+  fi
+}
+
+assert::git::not::has_changes() {
+  on_error=${1:-There are uncommitted changes in the working tree}
+  if [[ $(git::has_changes) ]]; then
+    sout::error "$on_error"
+    exit 1
+  fi
+}
+
+assert::git::on_master() {
+  on_error=${1:-Not in the master branch}
+  if [[ $(git::current_branch) -ne master ]]; then
+    sout::error "$on_error"
     exit 1
   fi
 }
