Git scripts

diff --git a/src/shell/string b/src/shell/string
--- a/src/shell/string
+++ b/src/shell/string
@@ -7,3 +7,12 @@ string::to_uppercase() {
 string::to_lowercase() {
   echo "$@" | tr [A-Z] [a-z]
 }
+
+string::is_a_number() {
+  re='^[0-9]+$'
+  if ! [[ $1 =~ $re ]]; then
+    echo "error: Not a number '$1'" >&2
+    return 2
+  fi
+  return 0
+}
